[package]
name = "ligma-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { version = "0.7.0" , features = ["getrandom"]}
log = "0.4"
rand = "0.8.5"
